/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as TermsRouteImport } from './app/terms'
import { Route as SettingsRouteImport } from './app/settings'
import { Route as ProfileRouteImport } from './app/profile'
import { Route as PrivacyRouteImport } from './app/privacy'
import { Route as KnowledgeRouteImport } from './app/knowledge'
import { Route as ChatRouteImport } from './app/chat'
import { Route as AdminRouteImport } from './app/admin'
import { Route as IndexRouteImport } from './app/index'
import { Route as KnowledgeIdRouteImport } from './app/knowledge.$id'
import { Route as AuthRegisterRouteImport } from './app/auth/register'
import { Route as AuthLoginRouteImport } from './app/auth/login'
import { Route as ApiWebSearchRouteImport } from './app/api/web-search'
import { Route as ApiFileParserRouteImport } from './app/api/file-parser'
import { Route as ApiKnowledgeIndexRouteImport } from './app/api/knowledge/index'
import { Route as ApiKnowledgeUploadRouteImport } from './app/api/knowledge/upload'
import { Route as ApiKnowledgeRetrieveRouteImport } from './app/api/knowledge/retrieve'
import { Route as ApiKnowledgeDocumentsRouteImport } from './app/api/knowledge/documents'
import { Route as ApiChatCompletionsRouteImport } from './app/api/chat/completions'
import { Route as ApiAuthSignupRouteImport } from './app/api/auth/signup'
import { Route as ApiAuthLoginRouteImport } from './app/api/auth/login'
import { Route as ApiAnalysisSummaryRouteImport } from './app/api/analysis/summary'
import { Route as ApiAnalysisStreamRouteImport } from './app/api/analysis/stream'
import { Route as ApiAdminUsersRouteImport } from './app/api/admin/users'
import { Route as ApiAdminSystemRouteImport } from './app/api/admin/system'
import { Route as ApiAdminStatsRouteImport } from './app/api/admin/stats'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIdRoute = KnowledgeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KnowledgeRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebSearchRoute = ApiWebSearchRouteImport.update({
  id: '/api/web-search',
  path: '/api/web-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileParserRoute = ApiFileParserRouteImport.update({
  id: '/api/file-parser',
  path: '/api/file-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeIndexRoute = ApiKnowledgeIndexRouteImport.update({
  id: '/api/knowledge/',
  path: '/api/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeUploadRoute = ApiKnowledgeUploadRouteImport.update({
  id: '/api/knowledge/upload',
  path: '/api/knowledge/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeRetrieveRoute = ApiKnowledgeRetrieveRouteImport.update({
  id: '/api/knowledge/retrieve',
  path: '/api/knowledge/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKnowledgeDocumentsRoute = ApiKnowledgeDocumentsRouteImport.update({
  id: '/api/knowledge/documents',
  path: '/api/knowledge/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCompletionsRoute = ApiChatCompletionsRouteImport.update({
  id: '/api/chat/completions',
  path: '/api/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalysisSummaryRoute = ApiAnalysisSummaryRouteImport.update({
  id: '/api/analysis/summary',
  path: '/api/analysis/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalysisStreamRoute = ApiAnalysisStreamRouteImport.update({
  id: '/api/analysis/stream',
  path: '/api/analysis/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSystemRoute = ApiAdminSystemRouteImport.update({
  id: '/api/admin/system',
  path: '/api/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/file-parser': typeof ApiFileParserRoute
  '/api/web-search': typeof ApiWebSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/system': typeof ApiAdminSystemRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/analysis/stream': typeof ApiAnalysisStreamRoute
  '/api/analysis/summary': typeof ApiAnalysisSummaryRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/chat/completions': typeof ApiChatCompletionsRoute
  '/api/knowledge/documents': typeof ApiKnowledgeDocumentsRoute
  '/api/knowledge/retrieve': typeof ApiKnowledgeRetrieveRoute
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/knowledge': typeof ApiKnowledgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/file-parser': typeof ApiFileParserRoute
  '/api/web-search': typeof ApiWebSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/system': typeof ApiAdminSystemRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/analysis/stream': typeof ApiAnalysisStreamRoute
  '/api/analysis/summary': typeof ApiAnalysisSummaryRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/chat/completions': typeof ApiChatCompletionsRoute
  '/api/knowledge/documents': typeof ApiKnowledgeDocumentsRoute
  '/api/knowledge/retrieve': typeof ApiKnowledgeRetrieveRoute
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/knowledge': typeof ApiKnowledgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/file-parser': typeof ApiFileParserRoute
  '/api/web-search': typeof ApiWebSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/system': typeof ApiAdminSystemRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/analysis/stream': typeof ApiAnalysisStreamRoute
  '/api/analysis/summary': typeof ApiAnalysisSummaryRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/chat/completions': typeof ApiChatCompletionsRoute
  '/api/knowledge/documents': typeof ApiKnowledgeDocumentsRoute
  '/api/knowledge/retrieve': typeof ApiKnowledgeRetrieveRoute
  '/api/knowledge/upload': typeof ApiKnowledgeUploadRoute
  '/api/knowledge/': typeof ApiKnowledgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/knowledge'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/api/file-parser'
    | '/api/web-search'
    | '/auth/login'
    | '/auth/register'
    | '/knowledge/$id'
    | '/api/admin/stats'
    | '/api/admin/system'
    | '/api/admin/users'
    | '/api/analysis/stream'
    | '/api/analysis/summary'
    | '/api/auth/login'
    | '/api/auth/signup'
    | '/api/chat/completions'
    | '/api/knowledge/documents'
    | '/api/knowledge/retrieve'
    | '/api/knowledge/upload'
    | '/api/knowledge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/knowledge'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/api/file-parser'
    | '/api/web-search'
    | '/auth/login'
    | '/auth/register'
    | '/knowledge/$id'
    | '/api/admin/stats'
    | '/api/admin/system'
    | '/api/admin/users'
    | '/api/analysis/stream'
    | '/api/analysis/summary'
    | '/api/auth/login'
    | '/api/auth/signup'
    | '/api/chat/completions'
    | '/api/knowledge/documents'
    | '/api/knowledge/retrieve'
    | '/api/knowledge/upload'
    | '/api/knowledge'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/knowledge'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/terms'
    | '/api/file-parser'
    | '/api/web-search'
    | '/auth/login'
    | '/auth/register'
    | '/knowledge/$id'
    | '/api/admin/stats'
    | '/api/admin/system'
    | '/api/admin/users'
    | '/api/analysis/stream'
    | '/api/analysis/summary'
    | '/api/auth/login'
    | '/api/auth/signup'
    | '/api/chat/completions'
    | '/api/knowledge/documents'
    | '/api/knowledge/retrieve'
    | '/api/knowledge/upload'
    | '/api/knowledge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiFileParserRoute: typeof ApiFileParserRoute
  ApiWebSearchRoute: typeof ApiWebSearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminSystemRoute: typeof ApiAdminSystemRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAnalysisStreamRoute: typeof ApiAnalysisStreamRoute
  ApiAnalysisSummaryRoute: typeof ApiAnalysisSummaryRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiChatCompletionsRoute: typeof ApiChatCompletionsRoute
  ApiKnowledgeDocumentsRoute: typeof ApiKnowledgeDocumentsRoute
  ApiKnowledgeRetrieveRoute: typeof ApiKnowledgeRetrieveRoute
  ApiKnowledgeUploadRoute: typeof ApiKnowledgeUploadRoute
  ApiKnowledgeIndexRoute: typeof ApiKnowledgeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$id': {
      id: '/knowledge/$id'
      path: '/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof KnowledgeIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-search': {
      id: '/api/web-search'
      path: '/api/web-search'
      fullPath: '/api/web-search'
      preLoaderRoute: typeof ApiWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-parser': {
      id: '/api/file-parser'
      path: '/api/file-parser'
      fullPath: '/api/file-parser'
      preLoaderRoute: typeof ApiFileParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/': {
      id: '/api/knowledge/'
      path: '/api/knowledge'
      fullPath: '/api/knowledge'
      preLoaderRoute: typeof ApiKnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/upload': {
      id: '/api/knowledge/upload'
      path: '/api/knowledge/upload'
      fullPath: '/api/knowledge/upload'
      preLoaderRoute: typeof ApiKnowledgeUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/retrieve': {
      id: '/api/knowledge/retrieve'
      path: '/api/knowledge/retrieve'
      fullPath: '/api/knowledge/retrieve'
      preLoaderRoute: typeof ApiKnowledgeRetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/knowledge/documents': {
      id: '/api/knowledge/documents'
      path: '/api/knowledge/documents'
      fullPath: '/api/knowledge/documents'
      preLoaderRoute: typeof ApiKnowledgeDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/completions': {
      id: '/api/chat/completions'
      path: '/api/chat/completions'
      fullPath: '/api/chat/completions'
      preLoaderRoute: typeof ApiChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis/summary': {
      id: '/api/analysis/summary'
      path: '/api/analysis/summary'
      fullPath: '/api/analysis/summary'
      preLoaderRoute: typeof ApiAnalysisSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis/stream': {
      id: '/api/analysis/stream'
      path: '/api/analysis/stream'
      fullPath: '/api/analysis/stream'
      preLoaderRoute: typeof ApiAnalysisStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/system': {
      id: '/api/admin/system'
      path: '/api/admin/system'
      fullPath: '/api/admin/system'
      preLoaderRoute: typeof ApiAdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeIdRoute: typeof KnowledgeIdRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeIdRoute: KnowledgeIdRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiFileParserRoute: ApiFileParserRoute,
  ApiWebSearchRoute: ApiWebSearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminSystemRoute: ApiAdminSystemRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAnalysisStreamRoute: ApiAnalysisStreamRoute,
  ApiAnalysisSummaryRoute: ApiAnalysisSummaryRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiChatCompletionsRoute: ApiChatCompletionsRoute,
  ApiKnowledgeDocumentsRoute: ApiKnowledgeDocumentsRoute,
  ApiKnowledgeRetrieveRoute: ApiKnowledgeRetrieveRoute,
  ApiKnowledgeUploadRoute: ApiKnowledgeUploadRoute,
  ApiKnowledgeIndexRoute: ApiKnowledgeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
